POST http://0.0.0.0:3000/rh/pessoa/2/telefone HTTP/1.1
content-type: application/json

{     
    
    "numero": "69-32382413"   
}

###

GET http://0.0.0.0:3000/rh/pai/1/filho
###

DELETE http://0.0.0.0:3000/rh/pessoa/5